services:
  # PostgreSQL
  postgres:
    image: postgres:15-alpine
    container_name: postgres_container
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    ports:
      - "${POSTGRES_PORT}:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - radar_network
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${POSTGRES_USER} -d ${POSTGRES_DB}"]
      interval: 5s
      timeout: 5s
      retries: 5
  redis:
    image: redis:7-alpine
    container_name: redis_container
    restart: always
    ports:
      - "${REDIS_PORT}:6379"
    volumes:
      - redis_data:/data
    networks:
      - radar_network
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 5s
      timeout: 3s
      retries: 5
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: app_container
    restart: on-failure
    ports:
      - "${APP_PORT}:${APP_PORT}"
    environment:
      - DB_HOST=postgres
      - DB_PORT=5432
      - DB_USER=${POSTGRES_USER}
      - DB_PASSWORD=${POSTGRES_PASSWORD}
      - DB_NAME=${POSTGRES_DB}
      - REDIS_PORT=6379
      - GIN_MODE=${GIN_MODE}
      - PORT=${APP_PORT}
    # запускаем сервис приложения только после проверки
    # работоспособности остальных сервисов
    depends_on:
      postgres:
        condition: service_healthy
      redis:
        condition: service_healthy
    networks:
      - radar_network
  migrator:
    image: migrate/migrate:v4.19.1
    container_name: event_migrator
    volumes:
      - "./migrations:/migrations"
    networks:
      - radar_network
    command: [
      "-path", "/migrations",
      "-database", "postgres://${POSTGRES_USER}:${POSTGRES_PASSWORD}@postgres_container:5432/${POSTGRES_DB}?sslmode=disable",
      "up"
    ]
    depends_on:
      postgres:
        condition: service_healthy
volumes:
  postgres_data:
  redis_data:

networks:
  radar_network:
    driver: bridge


