app:
  port: "8080"
  env: "development"

postgres:
  host: "postgres_container"
  port: 5432
  user: "radar_admin"
  db_name: "event_radar"

redis:
  host: "redis"
  port: 6379
jwt:
  access_token_ttl: 15m
  refresh_token_ttl: 720h
  
# jwt:
#   secret: "super_secret_jwtkey"
#   ttl_minutes: 15